@startuml
title PartyScript Classes

skinparam packageStyle node

package Counterparty {
  class CounterpartyAsset {
    +owner : Address
  }

  class MessageParser <<singleton>> {
    +parseMessage()
  }

  package PartyScript {
    package Storage {
      class KeyValuePair {
        +key
        +value
      }
      interface KeyValueGetAccess {
        +get()
      }
      interface KeyValueGetPutAccess extends KeyValueGetAccess {
        +put()
      }
      interface KeyValueTransaction {
        +transaction()
        +commit()
        +rollback()
      }
      class KeyValueStore <<singletion>> extends KeyValueTransaction, KeyValueGetPutAccess {
        {static} +getInstance() : KeyValueTransaction
        {static} +getInstance() : KeyValueGetPutAccess
        {static} +getInstance() : KeyValueGetAccess
      }
      KeyValueStore "1" *-- "n" KeyValuePair
    }
	MessageParser "1" o-- "1" KeyValueGetAccess
    package objects {
      package stack {
        class DataStack <<Stack>> {
        }
        class ExecStack <<Stack>> {
        }
        class CallStack <<Stack>> {
        }
      }


      CallStack "1" *-- "n" Environment
      MessageParser "0..1" *-- "1" Engine
      Scanner "1" o-- "1" KeyValueGetPutAccess

      Engine "1" o-- "1" KeyValueTransaction

      class Scriptlet {
        -data : Binary
        +new(: Binary)
        +getScriptlet() : Binary
      }

      class PartyScriptAsset extends CounterpartyAsset {
        getScriptlet() : Scriptlet
      }
      PartyScriptAsset "0..1" *-- "1" Scriptlet

      class Engine {
        +new(: PartyScriptAsset)
      }
      Engine "1" *-- "1" CallStack
      Engine "1" o-- "1" KeyValueStore

      class Environment {
        +new(asset: PartypScriptAsset)
        +scan()
      }
      Environment "1" o-- "1" PartyScriptAsset
      Environment "1" *-- "1" Scanner
      Environment "1" *-- "1" DataStack
      Environment "1" *-- "1" ExecStack

      class Scanner {
        -accepted : Boolean
        +new(: PartyScriptAsset, : Stack, : Stack)
        +scan()
        +isAccepted() : Boolean
      }
      Scanner "1" o-- "1" DataStack
      Scanner "1" o-- "1" ExecStack
      Scanner "1" o-- "1" KeyValueStore
      Scanner "1" o-- "1" PartyScriptAsset
    }
  }
}
